/* Category content + SEO copy for each Daroots weave.
   Written content is here so it's easy to edit in one place. */

export const CATEGORY_LIST = ['hand-tufted', 'hand-knotted', 'flat-weaves', 'handloom', 'coco-coir']

export const CATEGORIES = {
  'hand-tufted': {
    slug: 'hand-tufted',
    name: 'Hand Tufted',
    weave: 'Hand-Tufted Rugs',
    tag: 'Artistry underfoot',
    heroImg: '/rugs/ht.jpg',
    roomImg: '/rugs/room-ht.jpg',
    cardImg: '/rugs/ht.jpg',
    seoTitle: 'Hand Tufted Rugs, Custom Designer Wool Rugs | Daroots',
    seoDescription:
      'Daroots hand-tufted rugs: bold, painterly wool designs made to any pattern, colour, or shape. Custom artwork rugs and die-cut shapes, hand-finished and exported worldwide.',
    kicker: 'The design-first weave',
    headline: 'Hand Tufted Rugs',
    lede: 'When a design has no rules, we tuft it by hand: dense wool pile, saturated colour, and any silhouette you can draw.',
    intro: [
      'Hand tufting is where Daroots lets colour and imagination run free. Loops of wool are punched by hand into a stretched canvas with a tufting gun, following a design drawn to scale, then sheared, carved, and hand-finished into a plush, resilient pile. Because the pattern is painted rather than knotted row by row, there is almost no limit to what a hand-tufted rug can become: sweeping abstracts, photographic artwork, brand motifs, or a shape cut to your own outline.',
      'It is the fastest of our hand-made weaves to produce and the most versatile, which makes it the natural choice for statement floors, commercial interiors, and custom designs where the design leads. Every Daroots hand-tufted rug is backed, latexed, and cloth-finished for durability, then washed and clipped by hand so the colours sit true and the pile feels dense underfoot.',
    ],
    highlights: [
      ['Any design, any colour', 'Painterly abstracts, artwork, logos, or gradients. If it can be drawn, it can be tufted.'],
      ['Shaped & die-cut', 'Clouds, animals, blooms, or your own outline. Tufting frees the rug from the rectangle.'],
      ['Plush, dense pile', 'Hand-sheared wool with carved detailing for depth and a soft, resilient feel.'],
      ['Fast to bespoke', 'Shorter lead times than knotting, ideal for custom and contract projects at scale.'],
    ],
    specs: [
      ['Technique', 'Hand-tufted, cut & loop pile'],
      ['Material', 'New Zealand & highland wool, viscose highlights'],
      ['Backing', 'Cotton canvas, latexed & cloth-finished'],
      ['Sizes', 'Any size, plus custom & die-cut shapes'],
      ['Lead time', 'Typically 4-8 weeks'],
    ],
    products: [
      ['Artful Aura', 'Hand-tufted wool', '/rugs/ht-artful-aura.jpg'],
      ['Folk Story', 'Wool & viscose', '/rugs/ht-folk-story.jpg'],
      ['Leaf Line Grid', 'Hand-tufted wool', '/rugs/ht-leaf-line-grid.jpg'],
      ['Warm Blocks', 'Wool & viscose', '/rugs/ht-warm-blocks.jpg'],
      ['Bubbles', 'Hand-tufted wool', '/rugs/ht-bubbles.jpg'],
      ['City Lights', 'Wool & viscose', '/rugs/ht-city-lights.jpg'],
      ['Pencil Strokes', 'Hand-tufted wool', '/rugs/ht-pencil-strokes.jpg'],
      ['Town Lines', 'Wool & viscose', '/rugs/ht-town-lines.jpg'],
    ],
    faqs: [
      ['Can you make a rug in a custom shape?', 'Yes. Hand tufting can be cut to any silhouette: organic shapes, figures, logos, or a shape traced from your space.'],
      ['Can you reproduce my own artwork or a brand design?', 'We regularly tuft original artwork, brand motifs, and client designs. Share a reference and we render it to scale and match colours before production.'],
      ['How durable are hand-tufted rugs?', 'Very. Dense wool pile stands up to living rooms, hospitality, and high-traffic commercial floors.'],
    ],
  },

  'hand-knotted': {
    slug: 'hand-knotted',
    name: 'Hand Knotted',
    weave: 'Hand-Knotted Rugs',
    tag: 'The heirloom weave',
    heroImg: '/rugs/medallion.jpg',
    roomImg: '/rugs/room-hk.jpg',
    cardImg: '/rugs/medallion.jpg',
    seoTitle: 'Hand Knotted Rugs, Heirloom Persian & Moroccan Rugs | Daroots',
    seoDescription:
      'Daroots hand-knotted rugs: tied knot by knot in wool and silk over months. Persian medallions, Moroccan textures, and modern designs built to last generations. Exported worldwide.',
    kicker: 'Tied by hand, made to last',
    headline: 'Hand Knotted Rugs',
    lede: 'The oldest and most enduring rug we make. Every knot is tied by hand on the loom, over months, until it becomes an heirloom.',
    intro: [
      'A hand-knotted rug is the pinnacle of the weaver’s craft. On an upright loom, artisans tie each individual knot around the warp threads by hand, often more than a million knots in a single piece, reading a design point by point across weeks and months. Nothing about it is hurried, and nothing about it is mechanical. The result is a dense, supple rug that grows more beautiful with age and can pass down for generations.',
      'Daroots hand-knotted rugs span classic Persian medallions and all-over florals, softly textured Moroccan and Berber designs, and quiet contemporary pieces in hand-spun wool and lustrous silk. Every rug is knotted, hand-washed, sun-dried, and clipped in the weaving belt, then graded against a fixed standard before it leaves for export.',
    ],
    highlights: [
      ['Knot by knot', 'Each knot tied by hand: the densest, most durable construction we offer.'],
      ['Generational life', 'Made to be repaired, not replaced; a true heirloom that ages beautifully.'],
      ['Wool & mulberry silk', 'Hand-spun highland wool and fine silk for depth, sheen, and detail.'],
      ['Heritage & modern', 'Persian medallions, Moroccan texture, or restrained contemporary designs.'],
    ],
    specs: [
      ['Technique', 'Hand-knotted (Persian/Turkish knot)'],
      ['Knot density', 'Typically 100-400+ KPSI'],
      ['Material', 'Hand-spun wool, mulberry silk, cotton warp'],
      ['Sizes', 'Any size, including oversized & custom'],
      ['Lead time', 'Typically 4-9 months'],
    ],
    products: [
      ['Tabriz Medallion', 'Wool & silk', '/rugs/p-haveri.jpg'],
      ['Isfahan Garden', 'Hand-spun wool', '/rugs/p-hk1000.jpg'],
      ['Kashan Bloom', 'Wool, Moroccan', '/rugs/p-kemet.jpg'],
      ['Herati Vine', 'Wool & silk', '/rugs/p-madhubani.jpg'],
      ['Marrakesh Stone', 'High-low wool', '/rugs/p-moroccan.jpg'],
      ['Atlas Berber', 'Wool pile', '/rugs/p-morrican.jpg'],
      ['Bidjar Heirloom', 'Wool & silk', '/rugs/p-hk2.jpg'],
      ['Mithila Muse', 'Wool & silk', '/rugs/p-madhubani2.jpg'],
    ],
    faqs: [
      ['Why are hand-knotted rugs more expensive?', 'Each one takes months of skilled hand labour and over a million knots. You are buying an heirloom that lasts generations, not a disposable floor covering.'],
      ['How long will a hand-knotted rug last?', 'With normal care, decades to a century. They are designed to be professionally cleaned and even re-piled or repaired rather than replaced.'],
      ['Can I order a custom size or design?', 'Yes, any size, palette, or motif. Share your design and we weave it to your exact specification.'],
    ],
  },

  'flat-weaves': {
    slug: 'flat-weaves',
    name: 'Flat Weaves',
    weave: 'Flat-Weave Rugs',
    tag: 'Reversible & light',
    heroImg: '/rugs/fw.jpg',
    roomImg: '/rugs/room-fv.jpg',
    cardImg: '/rugs/fw.jpg',
    seoTitle: 'Flat Weave Rugs, Kilims, Dhurries & Kazak Rugs | Daroots',
    seoDescription:
      'Daroots flat-weave rugs: handwoven kilims, dhurries, and kazaks with bold geometry. Reversible, lightweight, and easy to live with, in wool and cotton, exported worldwide.',
    kicker: 'Pileless, reversible, graphic',
    headline: 'Flat Weave Rugs',
    lede: 'No pile, all pattern: kilims, dhurries, and kazaks woven flat, reversible, and rich with geometry.',
    intro: [
      'Flat weaves are woven, not knotted: the design is built directly from the interlaced warp and weft, so there is no pile at all. That makes them light, reversible, and wonderfully graphic: the same crisp geometry reads on both faces. From tribal kilims and Kazak medallions to fine cotton dhurries and modern ikat stripes, the flat-weave is the most relaxed and versatile rug in the Daroots range.',
      'Because they are thin and hard-wearing, flat weaves suit high-traffic spaces, layering over larger rugs, and rooms that call for pattern without weight. Every Daroots flat weave is handwoven in wool and cotton, finished with hand-tied fringes, and easy to lift, shake out, and live with.',
    ],
    highlights: [
      ['Reversible', 'Two usable faces; flip it to refresh a room or even out wear.'],
      ['Light & layerable', 'Thin and easy to move; perfect layered over a larger rug.'],
      ['Bold geometry', 'Kilim diamonds, Kazak medallions, ikat gradients, and clean stripes.'],
      ['Easy to live with', 'Hard-wearing and low-maintenance for busy, everyday spaces.'],
    ],
    specs: [
      ['Technique', 'Handwoven flat weave (kilim / dhurrie)'],
      ['Material', 'Wool pile-free, cotton warp'],
      ['Finish', 'Hand-tied fringes, reversible'],
      ['Sizes', 'Runners to room-size & custom'],
      ['Lead time', 'Typically 3-6 weeks'],
    ],
    products: [
      ['Shirvan Kazak', 'Wool kilim', '/rugs/p-kazak.jpg'],
      ['Anatolian Kilim', 'Wool kilim', '/rugs/p-kazak909.jpg'],
      ['Nomad Diamond', 'Wool kilim', '/rugs/p-kazak111.jpg'],
      ['Berber Dhurrie', 'Wool flatweave', '/rugs/p-kazak1020.jpg'],
      ['Cotton Stripe', 'Cotton dhurrie', '/rugs/p-stripes.jpg'],
      ['Panja Weave', 'Cotton & wool', '/rugs/p-ps04.jpg'],
      ['Sunset Ikat', 'Wool flatweave', '/rugs/p-ikat.jpg'],
      ['Ombre Ikat', 'Wool flatweave', '/rugs/p-ikat2.jpg'],
    ],
    faqs: [
      ['Are flat-weave rugs really reversible?', 'Yes. The pattern is woven through, so both sides are usable; flip the rug to even out wear or change the look.'],
      ['Do flat weaves need a rug pad?', 'We recommend one. Because they are thin and light, a pad keeps them from sliding and adds cushioning.'],
      ['Are they good for high-traffic areas?', 'Very. With no pile to crush, flat weaves are hard-wearing and easy to clean, ideal for hallways and busy rooms.'],
    ],
  },

  handloom: {
    slug: 'handloom',
    name: 'Handloom',
    weave: 'Handloom Rugs',
    tag: 'Modern texture',
    heroImg: '/rugs/hl.jpg',
    roomImg: '/rugs/room-hl.jpg',
    cardImg: '/rugs/hl.jpg',
    seoTitle: 'Handloom Rugs, Modern Textured & Melange Rugs | Daroots',
    seoDescription:
      'Daroots handloom rugs: loom-woven contemporary pieces with tactile texture and quiet melange colour. Wool, viscose, and natural fibres for modern interiors. Exported worldwide.',
    kicker: 'Contemporary & tactile',
    headline: 'Handloom Rugs',
    lede: 'Loom-woven for texture and calm: plain melange colour, subtle stripes, and a soft, tactile hand for modern rooms.',
    intro: [
      'Handloom rugs are woven on a traditional pit or frame loom, where the weaver draws each row of pile or flat weave by hand. The technique excels at the quieter end of design: rich melange colour, understated stripes and colour-blocks, and a range of textures, from soft cut pile to nubby, natural loops. It is the most contemporary weave in the Daroots range, made for interiors that want warmth and depth rather than a busy motif.',
      'We work handloom in wool, viscose, and blended natural fibres to hit the exact texture and sheen a space needs. Each rug is loom-woven, washed, and finished by hand: quiet, tactile pieces that ground a room and sit comfortably alongside modern furniture.',
    ],
    highlights: [
      ['Melange colour', 'Space-dyed yarns give depth and a lived-in, tonal richness.'],
      ['Texture-led', 'Cut pile, loops, and high-low surfaces you feel underfoot.'],
      ['Modern & calm', 'Plains, stripes, and colour-blocks that let the room breathe.'],
      ['Natural fibres', 'Wool, viscose, and blends tuned for softness and sheen.'],
    ],
    specs: [
      ['Technique', 'Handloom (pit / frame loom)'],
      ['Material', 'Wool, viscose, natural-fibre blends'],
      ['Texture', 'Cut pile, loop, and high-low'],
      ['Sizes', 'Any size & custom colourways'],
      ['Lead time', 'Typically 4-7 weeks'],
    ],
    products: [
      ['Highland Melange', 'Wool melange', '/rugs/hl.jpg'],
      ['Frost Loom', 'Wool melange', '/rugs/p-aspen5.jpg'],
      ['Slate Texture', 'Wool & viscose', '/rugs/p-aspen6.jpg'],
      ['Dune Weave', 'Wool melange', '/rugs/p-aspen.jpg'],
      ['Ember Melange', 'Wool & viscose', '/rugs/p-aspen8.jpg'],
      ['Teal Loom', 'Wool & viscose', '/rugs/p-teal.jpg'],
      ['Colour Field', 'Wool & viscose', '/rugs/p-colorblock.jpg'],
      ['Spectrum Blocks', 'Wool & viscose', '/rugs/p-colorblock2.jpg'],
    ],
    faqs: [
      ['What makes handloom different from hand-tufted?', 'Handloom is woven row by row on a loom (structure built into the weave), while tufting punches pile into a backing. Handloom suits texture and tonal colour; tufting suits bold, painted designs.'],
      ['Are handloom rugs soft?', 'Yes. We tune the fibre and pile for a soft, tactile hand, from plush cut pile to natural loops.'],
      ['Can I match a specific colour?', 'We space-dye and blend yarns to hit a target colourway for your piece.'],
    ],
  },

  'coco-coir': {
    slug: 'coco-coir',
    name: 'Coco & Coir',
    weave: 'Coco & Coir Rugs',
    tag: 'Natural & hard-wearing',
    heroImg: '/rugs/coco-strawberry.jpg',
    roomImg: '/rugs/coco-cats.jpg',
    cardImg: '/rugs/coco-cats.jpg',
    seoTitle: 'Coco & Coir Rugs, Natural Coconut Fibre Rugs & Mats | Daroots',
    seoDescription:
      'Daroots coco and coir rugs: hard-wearing natural coconut-fibre floor coverings, doormats, and area rugs. Rugged, eco-friendly texture in natural and bleached tones, exported worldwide.',
    kicker: 'Natural coconut fibre',
    headline: 'Coco & Coir Rugs',
    lede: 'Hard-wearing coconut-fibre doormats and mats: tough underfoot, naturally textured, and finished in clean naturals or playful printed designs.',
    intro: [
      'Coir is the coarse, springy fibre drawn from the husk of the coconut, and coco matting is one of the oldest natural floor coverings in the world. Twisted into hard yarns and woven on the loom, it makes a rug that is exceptionally tough, water-tolerant, and richly textured, the natural choice for entryways, hallways, verandas, and any floor that takes heavy footfall.',
      'At Daroots we weave coir on its own and blend it with cotton and jute for softer handloom pieces and defined borders. Left in its warm, undyed tone or bleached to a paler natural, coir brings an honest, grounding texture that layers beautifully under finer rugs and anchors relaxed, organic interiors.',
    ],
    highlights: [
      ['Built to last', 'Dense coconut-husk fibre shrugs off heavy foot traffic and rough use.'],
      ['Printed & shaped designs', 'Bold printed motifs and die-cut shapes, from strawberries to cats and dogs.'],
      ['Eco & renewable', 'A by-product of the coconut harvest: biodegradable and sustainable.'],
      ['Entryway-ready', 'Traps dirt and moisture, ideal for doormats, halls, and verandas.'],
    ],
    specs: [
      ['Technique', 'Loom-woven coir, coir & cotton blends'],
      ['Material', 'Coconut-husk coir, cotton & jute blends'],
      ['Finish', 'Natural or bleached tone, cotton-bound edges'],
      ['Best for', 'Entryways, halls, verandas, layering'],
      ['Lead time', 'Typically 3-6 weeks'],
    ],
    products: [
      ['Tabby Cat', 'Shaped coir doormat', '/rugs/coco-cat.jpg'],
      ['Cat Parade', 'Printed coir doormat', '/rugs/coco-cats.jpg'],
      ['Cool Cat', 'Round coir doormat', '/rugs/coco-coolcat.jpg'],
      ['Puppy', 'Shaped coir doormat', '/rugs/coco-dog.jpg'],
    ],
    faqs: [
      ['Are coir rugs hard-wearing?', 'Very. Coir is one of the toughest natural fibres, which is why it is used for doormats and high-traffic entryways. It stands up to heavy footfall for years.'],
      ['Where should I use a coco or coir rug?', 'They are ideal for entryways, hallways, kitchens, verandas, and covered outdoor areas, and they layer beautifully under a finer wool or silk rug.'],
      ['Can coir rugs be made to a custom size?', 'Yes. We weave coir to your size, with natural or bleached tone and optional cotton-bound borders.'],
    ],
  },
}
